/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as StockMarketUserIdLayoutImport } from './routes/stock-market/$userId/_layout'
import { Route as StockMarketUserIdLayoutUserImport } from './routes/stock-market/$userId/_layout.user'

// Create Virtual Routes

const StockMarketUserIdImport = createFileRoute('/stock-market/$userId')()

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StockMarketUserIdRoute = StockMarketUserIdImport.update({
  id: '/stock-market/$userId',
  path: '/stock-market/$userId',
  getParentRoute: () => rootRoute,
} as any)

const StockMarketUserIdLayoutRoute = StockMarketUserIdLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => StockMarketUserIdRoute,
} as any)

const StockMarketUserIdLayoutUserRoute =
  StockMarketUserIdLayoutUserImport.update({
    id: '/user',
    path: '/user',
    getParentRoute: () => StockMarketUserIdLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/stock-market/$userId': {
      id: '/stock-market/$userId'
      path: '/stock-market/$userId'
      fullPath: '/stock-market/$userId'
      preLoaderRoute: typeof StockMarketUserIdImport
      parentRoute: typeof rootRoute
    }
    '/stock-market/$userId/_layout': {
      id: '/stock-market/$userId/_layout'
      path: '/stock-market/$userId'
      fullPath: '/stock-market/$userId'
      preLoaderRoute: typeof StockMarketUserIdLayoutImport
      parentRoute: typeof StockMarketUserIdRoute
    }
    '/stock-market/$userId/_layout/user': {
      id: '/stock-market/$userId/_layout/user'
      path: '/user'
      fullPath: '/stock-market/$userId/user'
      preLoaderRoute: typeof StockMarketUserIdLayoutUserImport
      parentRoute: typeof StockMarketUserIdLayoutImport
    }
  }
}

// Create and export the route tree

interface StockMarketUserIdLayoutRouteChildren {
  StockMarketUserIdLayoutUserRoute: typeof StockMarketUserIdLayoutUserRoute
}

const StockMarketUserIdLayoutRouteChildren: StockMarketUserIdLayoutRouteChildren =
  {
    StockMarketUserIdLayoutUserRoute: StockMarketUserIdLayoutUserRoute,
  }

const StockMarketUserIdLayoutRouteWithChildren =
  StockMarketUserIdLayoutRoute._addFileChildren(
    StockMarketUserIdLayoutRouteChildren,
  )

interface StockMarketUserIdRouteChildren {
  StockMarketUserIdLayoutRoute: typeof StockMarketUserIdLayoutRouteWithChildren
}

const StockMarketUserIdRouteChildren: StockMarketUserIdRouteChildren = {
  StockMarketUserIdLayoutRoute: StockMarketUserIdLayoutRouteWithChildren,
}

const StockMarketUserIdRouteWithChildren =
  StockMarketUserIdRoute._addFileChildren(StockMarketUserIdRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stock-market/$userId': typeof StockMarketUserIdLayoutRouteWithChildren
  '/stock-market/$userId/user': typeof StockMarketUserIdLayoutUserRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stock-market/$userId': typeof StockMarketUserIdLayoutRouteWithChildren
  '/stock-market/$userId/user': typeof StockMarketUserIdLayoutUserRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stock-market/$userId': typeof StockMarketUserIdRouteWithChildren
  '/stock-market/$userId/_layout': typeof StockMarketUserIdLayoutRouteWithChildren
  '/stock-market/$userId/_layout/user': typeof StockMarketUserIdLayoutUserRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/stock-market/$userId'
    | '/stock-market/$userId/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/stock-market/$userId'
    | '/stock-market/$userId/user'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/stock-market/$userId'
    | '/stock-market/$userId/_layout'
    | '/stock-market/$userId/_layout/user'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StockMarketUserIdRoute: typeof StockMarketUserIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StockMarketUserIdRoute: StockMarketUserIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/login",
        "/register",
        "/stock-market/$userId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/stock-market/$userId": {
      "filePath": "stock-market/$userId",
      "children": [
        "/stock-market/$userId/_layout"
      ]
    },
    "/stock-market/$userId/_layout": {
      "filePath": "stock-market/$userId/_layout.tsx",
      "parent": "/stock-market/$userId",
      "children": [
        "/stock-market/$userId/_layout/user"
      ]
    },
    "/stock-market/$userId/_layout/user": {
      "filePath": "stock-market/$userId/_layout.user.tsx",
      "parent": "/stock-market/$userId/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
