import { hc } from 'hono/client';
import { type WebSocketApp } from '../../server';
import createClient from "openapi-fetch";
import type { paths } from "./apitype"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: import.meta.env['PROD'] ? 'https://bun.hashmani.taskmate.ae/api/model' : 'http://localhost:3061/api/model' });

export const hclient = hc<WebSocketApp>(import.meta.env['PROD'] ? 'https://bun.hashmani.taskmate.ae' : 'http://localhost:3061');