name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main # Change to your default branch if needed

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust based on your project requirements

      - name: Install Dependencies
        run: npm install

      - name: Build Static Site
        run: npm run build

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Sync with S3
        run: |
          aws s3 sync ./client/dist s3://${{ secrets.S3_BUCKET_NAME }} \
            --delete \
            --acl public-read # Optional: Ensure appropriate permissions

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"